-- AmmoConverterCatalog.generated.lua
-- AUTO-GENERATED by com.modelus.ammoconverter.AmmoConverterLuaGenerator
-- DO NOT EDIT MANUALLY — edit AmmoConverterConfig.java instead.
-- Re-generate with: ./gradlew generateAmmoConverterLua

AmmoConverterCatalog_Generated = {}

AmmoConverterCatalog_Generated.AMMO_TYPES = {
    "Base.Bullets9mm",
    "Base.Bullets38",
    "Base.Bullets45",
    "Base.Bullets357",
    "Base.Bullets44",
    "Base.556Bullets",
    "Base.308Bullets",
    "Base.3030Bullets",
    "Base.ShotgunShells",
}

AmmoConverterCatalog_Generated.SCRIPT_TO_FULL_TYPE = {
    ["base:bullets_556"] = "Base.556Bullets",
    ["base:bullets_3030"] = "Base.3030Bullets",
    ["base:bullets_308"] = "Base.308Bullets",
    ["base:bullets_44"] = "Base.Bullets44",
    ["base:bullets_9mm"] = "Base.Bullets9mm",
    ["base:bullets_38"] = "Base.Bullets38",
    ["base:bullets_45"] = "Base.Bullets45",
    ["base:bullets_357"] = "Base.Bullets357",
    ["base:shotgun_shells"] = "Base.ShotgunShells",
}

AmmoConverterCatalog_Generated.PACKAGING = {
    ["Base.556Bullets"] = { box = "Base.556Box", carton = "Base.556Carton", boxValue = 20, cartonValue = 240 },
    ["Base.3030Bullets"] = { box = "Base.3030Box", carton = "Base.3030Carton", boxValue = 20, cartonValue = 240 },
    ["Base.308Bullets"] = { box = "Base.308Box", carton = "Base.308Carton", boxValue = 20, cartonValue = 240 },
    ["Base.Bullets44"] = { box = "Base.Bullets44Box", carton = "Base.Bullets44Carton", boxValue = 20, cartonValue = 240 },
    ["Base.Bullets9mm"] = { box = "Base.Bullets9mmBox", carton = "Base.Bullets9mmCarton", boxValue = 50, cartonValue = 600 },
    ["Base.Bullets38"] = { box = "Base.Bullets38Box", carton = "Base.Bullets38Carton", boxValue = 50, cartonValue = 600 },
    ["Base.Bullets45"] = { box = "Base.Bullets45Box", carton = "Base.Bullets45Carton", boxValue = 50, cartonValue = 600 },
    ["Base.Bullets357"] = { box = "Base.Bullets357Box", carton = "Base.Bullets357Carton", boxValue = 50, cartonValue = 600 },
    ["Base.ShotgunShells"] = { box = "Base.ShotgunShellsBox", carton = "Base.ShotgunShellsCarton", boxValue = 25, cartonValue = 300 },
}

AmmoConverterCatalog_Generated.TIERS = {
    universal = {
        "Base.Bullets9mm",
        "Base.Bullets38",
        "Base.Bullets45",
        "Base.Bullets357",
        "Base.Bullets44",
        "Base.556Bullets",
        "Base.308Bullets",
        "Base.3030Bullets",
        "Base.ShotgunShells",
    },
}

AmmoConverterCatalog_Generated._lookup = {}
for _, fullType in ipairs(AmmoConverterCatalog_Generated.AMMO_TYPES) do
    AmmoConverterCatalog_Generated._lookup[fullType] = true
end
