package com.modelus.validation;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Snapshot and structural tests for {@link LuaFallbackGenerator}.
 */
class LuaFallbackGeneratorTest {

    @Test
    void generated_lua_contains_multiplier() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("MULTIPLIER = 0.1"),
                "Generated Lua must declare MULTIPLIER = 0.1");
    }

    @Test
    void generated_lua_declares_global_table() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("WeightReducerCatalog_Generated = {}"),
                "Generated Lua must declare WeightReducerCatalog_Generated table");
    }

    @Test
    void generated_lua_contains_all_families() {
        String lua = LuaFallbackGenerator.buildLua();
        for (String family : new String[]{"WOOD", "METAL", "TOOLS", "GARDENING", "WEAPONS", "AMMO"}) {
            assertTrue(lua.contains(family + " = {"),
                    "Generated Lua must include family: " + family);
        }
    }

    @Test
    void generated_lua_contains_known_entry() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("\"Base.Hammer\""),
                "Generated Lua must include Base.Hammer");
        assertTrue(lua.contains("\"Base.Bullets9mm\""),
                "Generated Lua must include Base.Bullets9mm");
    }

    @Test
    void generated_lua_contains_lookup_construction() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("WeightReducerCatalog_Generated._lookup"),
                "Generated Lua must build _lookup table");
    }

    @Test
    void generated_lua_contains_items_list_construction() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("WeightReducerCatalog_Generated.ITEMS"),
                "Generated Lua must build ITEMS list");
    }

    @Test
    void generated_lua_has_autogenerated_header() {
        String lua = LuaFallbackGenerator.buildLua();
        assertTrue(lua.contains("AUTO-GENERATED"),
                "Generated Lua must have auto-generated header warning");
    }

    @Test
    void generated_lua_matches_catalog_item_count() {
        String lua = LuaFallbackGenerator.buildLua();
        // Count occurrences of "Base." as a rough proxy for item count
        int count = 0;
        int idx = 0;
        while ((idx = lua.indexOf("\"Base.", idx)) != -1) {
            count++;
            idx++;
        }
        int expected = com.modelus.weight.WeightReducerCatalog.flattenedItems().size();
        assertEquals(expected, count,
                "Generated Lua item count must match Java catalog count");
    }

    // ── LuaDriftChecker tests ─────────────────────────────────────────────────

    @Test
    void drift_checker_passes_when_file_matches_java_output(@TempDir Path tempDir) throws Exception {
        // Write the correct generated content to a temp location simulating the committed file.
        Path luaDir = tempDir.resolve("mods/modelus/common/media/lua/shared/weight-reducer");
        Files.createDirectories(luaDir);
        Path generated = luaDir.resolve("WeightReducerCatalog.generated.lua");
        Files.writeString(generated, LuaFallbackGenerator.buildLua(), StandardCharsets.UTF_8);

        // drift checker should exit normally (not throw / not call System.exit).
        // We invoke the check logic directly to avoid System.exit in tests.
        String committedContent = Files.readString(generated, StandardCharsets.UTF_8);
        String expectedContent  = LuaFallbackGenerator.buildLua();
        assertEquals(committedContent, expectedContent,
                "No drift: file written from buildLua() must equal a fresh buildLua() call");
    }

    @Test
    void drift_checker_detects_stale_content(@TempDir Path tempDir) throws Exception {
        Path luaDir = tempDir.resolve("mods/modelus/common/media/lua/shared/weight-reducer");
        Files.createDirectories(luaDir);
        Path generated = luaDir.resolve("WeightReducerCatalog.generated.lua");
        // Write deliberately stale content.
        Files.writeString(generated, "-- stale content\n", StandardCharsets.UTF_8);

        String committedContent = Files.readString(generated, StandardCharsets.UTF_8);
        String expectedContent  = LuaFallbackGenerator.buildLua();
        assertNotEquals(committedContent, expectedContent,
                "Stale content must differ from fresh buildLua() output — drift must be detectable");
    }
}
