package com.modelus.validation;

import com.modelus.weight.WeightReducerCatalog;
import com.modelus.weight.WeightReducerCatalog.CatalogEntry;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Generates a deterministic Lua fallback file from the Java {@link WeightReducerCatalog}.
 *
 * <p>The generated file is placed at
 * {@code mods/modelus/common/media/lua/shared/weight-reducer/WeightReducerCatalog.generated.lua}
 * relative to the project root.  It contains read-only static data:
 * multiplier, family names, flat item list, and lookup table.</p>
 *
 * <p>The generated file is overwritten on every build.  Do NOT edit it manually —
 * edit the Java catalog instead.</p>
 *
 * <p>This class is called by the {@code generateWeightReducerLua} Gradle task.</p>
 */
public final class LuaFallbackGenerator {

    /** Relative path from project root to the generated file. */
    public static final String GENERATED_LUA_REL_PATH =
            "mods/modelus/common/media/lua/shared/weight-reducer/WeightReducerCatalog.generated.lua";

    private LuaFallbackGenerator() {
    }

    /**
     * Generate the Lua fallback and write it to {@code outputPath}.
     *
     * @param outputPath absolute path where the generated file will be written.
     * @throws IOException if the file cannot be written.
     */
    public static void generate(Path outputPath) throws IOException {
        String lua = buildLua();
        Files.createDirectories(outputPath.getParent());
        Files.writeString(outputPath, lua, StandardCharsets.UTF_8);
        System.out.println("[LuaFallbackGenerator] Generated: " + outputPath);
    }

    /** Return the generated Lua source as a string (useful for tests / snapshot). */
    public static String buildLua() {
        StringBuilder sb = new StringBuilder();

        sb.append("-- WeightReducerCatalog.generated.lua\n");
        sb.append("-- AUTO-GENERATED by com.modelus.validation.LuaFallbackGenerator\n");
        sb.append("-- DO NOT EDIT MANUALLY — edit WeightReducerCatalog.java instead.\n");
        sb.append("-- Re-generate with: ./gradlew generateWeightReducerLua\n");
        sb.append("\n");
        sb.append("WeightReducerCatalog_Generated = {}\n");
        sb.append("\n");

        // Multiplier
        sb.append(String.format(Locale.ROOT, "WeightReducerCatalog_Generated.MULTIPLIER = %.1f%n",
                WeightReducerCatalog.MULTIPLIER));
        sb.append("\n");

        // ITEMS_BY_FAMILY
        sb.append("WeightReducerCatalog_Generated.ITEMS_BY_FAMILY = {\n");
        for (Map.Entry<String, List<CatalogEntry>> familyEntry
                : WeightReducerCatalog.entriesByFamily().entrySet()) {
            String family = familyEntry.getKey();
            List<CatalogEntry> entries = familyEntry.getValue();

            sb.append("    ").append(family).append(" = {\n");
            for (CatalogEntry entry : entries) {
                sb.append("        \"").append(entry.fullType()).append("\",\n");
            }
            sb.append("    },\n");
        }
        sb.append("}\n");
        sb.append("\n");

        // Flat ITEMS list
        sb.append("WeightReducerCatalog_Generated.ITEMS = {}\n");
        sb.append("for _, group in pairs(WeightReducerCatalog_Generated.ITEMS_BY_FAMILY) do\n");
        sb.append("    for _, fullType in ipairs(group) do\n");
        sb.append("        WeightReducerCatalog_Generated.ITEMS[#WeightReducerCatalog_Generated.ITEMS + 1] = fullType\n");
        sb.append("    end\n");
        sb.append("end\n");
        sb.append("\n");

        // Lookup table
        sb.append("WeightReducerCatalog_Generated._lookup = {}\n");
        sb.append("for _, fullType in ipairs(WeightReducerCatalog_Generated.ITEMS) do\n");
        sb.append("    WeightReducerCatalog_Generated._lookup[fullType] = true\n");
        sb.append("end\n");

        return sb.toString();
    }

    public static void main(String[] args) throws IOException {
        String projectRoot = args.length > 0 ? args[0] : ".";
        Path output = Path.of(projectRoot).resolve(GENERATED_LUA_REL_PATH).toAbsolutePath();
        generate(output);
    }
}
