package com.modelus.ammoconverter;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/** Generates the Lua ammo-converter catalog from Java source-of-truth config. */
public final class AmmoConverterLuaGenerator {

  public static final String GENERATED_LUA_REL_PATH =
      "mods/modelus/common/media/lua/shared/ammo-converter/AmmoConverterCatalog.generated.lua";

  private AmmoConverterLuaGenerator() {
  }

  public static void generate(Path outputPath) throws IOException {
    Files.createDirectories(outputPath.getParent());
    Files.writeString(outputPath, buildLua(), StandardCharsets.UTF_8);
    System.out.println("[AmmoConverterLuaGenerator] Generated: " + outputPath);
  }

  public static String buildLua() {
    StringBuilder sb = new StringBuilder();
    sb.append("-- AmmoConverterCatalog.generated.lua\n");
    sb.append("-- AUTO-GENERATED by com.modelus.ammoconverter.AmmoConverterLuaGenerator\n");
    sb.append("-- DO NOT EDIT MANUALLY — edit AmmoConverterConfig.java instead.\n");
    sb.append("-- Re-generate with: ./gradlew generateAmmoConverterLua\n\n");
    sb.append("AmmoConverterCatalog_Generated = {}\n\n");

    appendAmmoTypes(sb);
    appendScriptMap(sb);
    appendPackaging(sb);
    appendTiers(sb);
    appendLookup(sb);

    return sb.toString();
  }

  private static void appendAmmoTypes(StringBuilder sb) {
    sb.append("AmmoConverterCatalog_Generated.AMMO_TYPES = {\n");
    for (String type : AmmoConverterConfig.TIERS.get("universal")) {
      sb.append("    \"").append(type).append("\",\n");
    }
    sb.append("}\n\n");
  }

  private static void appendScriptMap(StringBuilder sb) {
    sb.append("AmmoConverterCatalog_Generated.SCRIPT_TO_FULL_TYPE = {\n");
    for (Map.Entry<String, String> entry : AmmoConverterConfig.SCRIPT_TO_FULL_TYPE.entrySet()) {
      sb.append("    [\"").append(entry.getKey()).append("\"] = \"")
          .append(entry.getValue()).append("\",\n");
    }
    sb.append("}\n\n");
  }

  private static void appendPackaging(StringBuilder sb) {
    sb.append("AmmoConverterCatalog_Generated.PACKAGING = {\n");
    for (Map.Entry<String, AmmoConverterConfig.PackageDef> entry : AmmoConverterConfig.PACKAGING.entrySet()) {
      AmmoConverterConfig.PackageDef pkg = entry.getValue();
      sb.append("    [\"").append(entry.getKey()).append("\"] = { box = \"")
          .append(pkg.box()).append("\", carton = \"").append(pkg.carton())
          .append("\", boxValue = ").append(pkg.boxValue())
          .append(", cartonValue = ").append(pkg.cartonValue()).append(" },\n");
    }
    sb.append("}\n\n");
  }

  private static void appendTiers(StringBuilder sb) {
    sb.append("AmmoConverterCatalog_Generated.TIERS = {\n");
    for (Map.Entry<String, List<String>> entry : AmmoConverterConfig.TIERS.entrySet()) {
      sb.append("    ").append(entry.getKey()).append(" = {\n");
      for (String type : entry.getValue()) {
        sb.append("        \"").append(type).append("\",\n");
      }
      sb.append("    },\n");
    }
    sb.append("}\n\n");
  }

  private static void appendLookup(StringBuilder sb) {
    sb.append("AmmoConverterCatalog_Generated._lookup = {}\n");
    sb.append("for _, fullType in ipairs(AmmoConverterCatalog_Generated.AMMO_TYPES) do\n");
    sb.append("    AmmoConverterCatalog_Generated._lookup[fullType] = true\n");
    sb.append("end\n");
  }

  public static void main(String[] args) throws IOException {
    String projectRoot = args.length > 0 ? args[0] : ".";
    Path output = Path.of(projectRoot).resolve(GENERATED_LUA_REL_PATH).toAbsolutePath();
    generate(output);
  }
}
